### ISSUE TITLE
Any plans to create a Metrics Plugin?

### ISSUE THREAD

**Issue by labmonkey** [arkmq-org/activemq-artemis-broker-kubernetes-image#83]
Hello. I was browsing this project and since the repositories are based on the equivalents from RedHat AMQ Broker I was wondering if there is any reason why the Metrics plugin is still using the one published by RedHat instead of having its own "mirrored" one  in artemiscloud just like other repositories? Generally I am asking if there are plans to create this plugin repository here.

https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/blob/89a5d7600961569c4e3eef0541d977e57d6d5777/modules/activemq-artemis-launch/added/launch.sh#L299

**Comment by tlbueno** [comment]
Hi @labmonkey 
Currently it's the opposite. RedHat AMQ Broker Operator is based on ArtemisCloud project and RedHat AMQ Broker is based on Apache ActiveMQ Artemis. 

Currently there is no plan to have the ArtemisPrometheusMetricsPlugin under ArtemisCloud project since the project from RedHat is [open source][1], has [Apache license][2] and its artifacts are published in RedHat public [maven repository][3].

@brusdev ^^

[1]: https://github.com/rh-messaging/artemis-prometheus-metrics-plugin
[2]: https://github.com/rh-messaging/artemis-prometheus-metrics-plugin/blob/main/LICENSE
[3]: https://maven.repository.redhat.com/ga/com/redhat/amq-broker/artemis-prometheus-metrics-plugin/
